# Generated by Django 3.1.5 on 2021-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('date', models.DateField(verbose_name='Дата высадки')),
                ('type', models.CharField(max_length=1000, verbose_name='Tип')),
            ],
            options={
                'verbose_name': 'Растения',
                'verbose_name_plural': 'Растения',
            },
        ),
    ]
