# Generated by Django 3.1.5 on 2021-01-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20210106_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigation',
            name='time',
            field=models.TimeField(default='00:00', verbose_name='Время полива'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='date',
            field=models.IntegerField(choices=[(1, 'Каждый день'), (2, 'Два раза в неделю'), (3, 'Три раза в неделю'), (4, 'Раз в месяц')]),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.articles', verbose_name='Растение'),
        ),
    ]
