# Generated by Django 3.1.5 on 2021-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210106_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='date',
            field=models.CharField(choices=[('Каждый день', 'Каждый день'), ('Два раза в неделю', 'Два раза в неделю'), ('Три раза в неделю', 'Три раза в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=100, verbose_name='Частота полива'),
        ),
    ]
