# Generated by Django 3.1.5 on 2021-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20210106_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фирмы')),
                ('adress', models.CharField(max_length=100, verbose_name='Юридический адрес')),
            ],
            options={
                'verbose_name': 'Фирмы',
                'verbose_name_plural': 'Фирмы',
            },
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Частота полива'),
        ),
    ]
