# Generated by Django 3.1.5 on 2021-01-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20210106_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firms',
            options={'verbose_name': 'Фирма', 'verbose_name_plural': 'Фирмы'},
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.IntegerField(max_length=11, verbose_name='Телефон')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.firms', verbose_name='Фирма')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.articles', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
            },
        ),
    ]
