# Generated by Django 3.1.5 on 2021-01-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20210106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.articles', verbose_name='ID Растение'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.firms', verbose_name='Фирмы'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.articles', verbose_name='Растения'),
        ),
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.IntegerField(max_length=11, verbose_name='Телефон')),
                ('VUZ', models.CharField(max_length=100, verbose_name='ВУЗ')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.firms', verbose_name='Фирмы')),
            ],
            options={
                'verbose_name': 'Декоратор',
                'verbose_name_plural': 'Декораторы',
            },
        ),
    ]
