# Generated by Django 3.1.5 on 2021-01-06 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20210107_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата работы с насаждением')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
