# Generated by Django 3.1.5 on 2021-01-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.worker', verbose_name='Рабочий'),
        ),
    ]
