# Generated by Django 3.1.5 on 2021-01-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20210107_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.IntegerField(max_length=255, verbose_name='Телефон'),
        ),
    ]
