# Generated by Django 3.1.5 on 2021-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20210107_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Plants',
        ),
        migrations.AddField(
            model_name='decorator',
            name='ed',
            field=models.CharField(default='Образование', max_length=255, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='decorator',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
    ]
